from __future__ import annotations
from dataclasses import dataclass
from typing import Any, TYPE_CHECKING
from athena.ai.model import PokerModel, PredictionResult
from athena.core.features import FeatureEncoder
from athena.core.decision import DecisionContext

if TYPE_CHECKING:
    from athena.core.game_state import GameState


@dataclass(frozen=True, slots=True)
class DecisionResponse:
    """Represents the service-layer decision output derived from an AI model prediction.
    
    Attributes:
        action: Recommended action string (e.g., 'BET', 'FOLD', 'CALL').
        confidence: Degree of certainty in prediction (0.0 to 1.0).
        reasoning: Explanation or source model metadata.
    """
    action: str
    confidence: float
    reasoning: str

    def __post_init__(self) -> None:
        """Validates DecisionResponse field constraints."""
        if not isinstance(self.action, str) or not self.action.strip():
            raise ValueError("action must be a non-empty string.")
        if not (0.0 <= self.confidence <= 1.0):
            raise ValueError(f"confidence must be between 0.0 and 1.0. Got: {self.confidence}")


class DecisionEngine:
    """Service layer orchestrator that bridges Game State, Feature Engineering Layer, 
    and AI Models to generate actionable poker decisions.
    """

    def __init__(self, model: PokerModel) -> None:
        """Initializes the DecisionEngine with a concrete PokerModel instance.
        
        Args:
            model: An instance implementing the PokerModel interface.
            
        Raises:
            ValueError: If model is None.
        """
        if model is None:
            raise ValueError("model cannot be None.")
        self._model: PokerModel = model
        self._feature_encoder: FeatureEncoder = FeatureEncoder()

    def decide(self, game_state: Any) -> DecisionResponse:
        """Takes a GameState (or DecisionContext), converts it to features, 
        queries the AI model, and returns a structured DecisionResponse.
        
        Args:
            game_state: GameState or DecisionContext representing the current table state.
            
        Returns:
            DecisionResponse containing action, confidence, and reasoning.
        """
        # Step 1 & 2: Normalize game state to DecisionContext and extract feature vector
        context = self._convert_to_decision_context(game_state)
        feature_vector = self._feature_encoder.create_vector(context)
        features_list = feature_vector.to_tuple()

        # Step 3: Send features to model.predict()
        prediction: PredictionResult = self._model.predict(features_list)

        # Step 4: Convert prediction result into service-layer DecisionResponse
        return DecisionResponse(
            action=prediction.action,
            confidence=prediction.confidence,
            reasoning=f"Generated by {prediction.model_name} ({prediction.model_version})."
        )

    def _convert_to_decision_context(self, game_state: Any) -> DecisionContext:
        """Safely maps a GameState object or dictionary into a DecisionContext."""
        if isinstance(game_state, DecisionContext):
            return game_state

        stack_bb = float(getattr(game_state, "stack_bb", getattr(game_state, "stack", 40.0)))
        pot_bb = float(getattr(game_state, "pot_bb", getattr(game_state, "pot", 10.0)))
        position = str(getattr(game_state, "position", "BTN"))
        street = str(getattr(game_state, "street", "PREFLOP"))
        opponents = int(getattr(game_state, "opponents", 1))
        current_bet_bb = float(getattr(game_state, "current_bet_bb", getattr(game_state, "current_bet", 0.0)))
        hand_strength = float(getattr(game_state, "hand_strength", 0.5))
        tournament_stage = str(getattr(game_state, "tournament_stage", "MIDDLE"))

        return DecisionContext(
            stack_bb=stack_bb,
            pot_bb=pot_bb,
            position=position,
            street=street,
            opponents=opponents,
            current_bet_bb=current_bet_bb,
            hand_strength=hand_strength,
            tournament_stage=tournament_stage,
        )